
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginxapp
        image: tridevg/nginx-july:v1
        ports:
        - containerPort: 80

